batchSize: 256
constantOffsetSD: 0.2
d_model: 256
dataset: /data/engs-pnpl/kebl7765/willett2023/competitionData/pytorchTFRecords.pkl
device: cuda
experimentPath: /data/engs-pnpl/trin4076/Sequence-Models/results
gaussianSmoothWidth: 2.0
l2_decay: 0 
log_wandb: true
lr: 0.002
lrEnd: 0.0002
lrFinder: false
modelName: mamba_5_layers_16_d_state_4_d_conv_2_expand
modelType: s4
nClasses: 40
nEpochs: 50
nHiddenFeatures: 256 
nInputFeatures: 256 
nLayers: 5 
partition: short
pppipeline: false
resume: null
seed: 0
useScheduler: true
whiteNoiseSD: 0.8
