baseDir: /data/engs-pnpl/kebl7765/willett2023/
batchSize: 64
bias: false
constantOffsetSD: 0.2
conv_bias: true
d_conv: 4
d_state: 16
dataset: /data/engs-pnpl/kebl7765/willett2023/competitionData/pytorchTFRecords.pkl
device: cuda
dt_init: random
dt_init_floor: 0.0001
dt_max: 0.1
dt_min: 0.001
dt_rank: auto
dt_scale: 1.0
expand: 2
experimentPath: /data/engs-pnpl/trin4076/Sequence-Models/results
gaussianSmoothWidth: 2.0
l2_decay: 1.0e-05
log_wandb: true
lr: 0.002
lrEnd: 0.0002
lrFinder: false
mem: 16
modelName: mamba_5_layers_16_d_state_4_d_conv_2_expand
modelType: mamba
nClasses: 40
nEpochs: 50
nHiddenFeatures: 256
nInputFeatures: 256
nLayers: 5
nParams: 2191872
partition: short
pppipeline: false
resume: null
seed: 0
time: 0-04:00:00
useScheduler: true
use_fast_path: true
whiteNoiseSD: 0.8
