batchSize: 64
constantOffsetSD: 0.2
d_model: 256
dataset: /data/engs-pnpl/kebl7765/willett2023/competitionData/pytorchTFRecords.pkl
device: cuda
experimentPath: /data/engs-pnpl/trin4076/Sequence-Models/results
gaussianSmoothWidth: 2.0
weightDecay: 0 
log_wandb: true
lr: 0.0005
lrEnd: 0.0002
lrFinder: false
modelType: s4
nClasses: 40
nEpochs: 100
nHiddenFeatures: 256 
nInputFeatures: 256 
nLayers: 8
pppipeline: false
resume: null
seed: 0
useScheduler: true
whiteNoiseSD: 0.8
